walkframe := 7

walkDown := [["d",walkframe]
    ,["w",34]]

walkUp := [["u",walkframe]
    ,["w",34]]

walkLeft := [["l",walkframe]
    ,["w",34]]

walkRight := [["r",walkframe]
    ,["w",34]]

grassDown := [["d",walkframe]
    ,["w",800]
    ,["x",3]
    ,["w",34]
    ,["l",3]
    ,["w",24]
    ,["r",3]
    ,["w",24]
    ,["a",3]
    ,["w",420]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]]

grassRight := [["r",walkframe]
    ,["w",800]
    ,["x",3]
    ,["w",60]
    ,["l",3]
    ,["w",24]
    ,["r",3]
    ,["w",24]
    ,["a",3]
    ,["w",420]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]]

grassUp := [["u",walkframe]
    ,["w",800]
    ,["x",3]
    ,["w",60]
    ,["l",3]
    ,["w",24]
    ,["r",3]
    ,["w",24]
    ,["a",3]
    ,["w",420]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]]

grassLeft := [["l",walkframe]
    ,["w",800]
    ,["x",3]
    ,["w",60]
    ,["l",3]
    ,["w",24]
    ,["r",3]
    ,["w",24]
    ,["a",3]
    ,["w",420]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]
    ,["b",5]
    ,["w",60]]


flounder := [["u",1]
    ,["w",34]
    ,["r",1]
    ,["w",34]
    ,["d",1]
    ,["w",34]
    ,["l",1]
    ,["w",34]]

talkB := [["b",5]
    ,["w",90]]

talkA := [["a",5]
    ,["w",90]]



pokemonCenter := [["u",walkframe]
    ,["w",34]
    ,["u",walkframe]
    ,["w",34]
    ,["u",walkframe]
    ,["w",34]
    ,["u",walkframe]
    ,["w",34]
    ,["u",walkframe]
    ,["w",34]
    ,["u",walkframe]
    ,["w",34]
    ,["u",walkframe]
    ,["w",34]
    ,["a",5]
    ,["w",90]
    ,["a",5]
    ,["w",90]
    ,["a",5]
    ,["w",90]
    ,["a",5]
    ,["w",90]
    ,["a",5]
    ,["w",600]
    ,["a",5]
    ,["w",90]
    ,["a",5]
    ,["w",90]
    ,["a",5]
    ,["w",90]
    ,["b",5]
    ,["w",90]
    ,["b",5]
    ,["w",90]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",34]
    ,["d",walkframe]
    ,["w",240]]



macros := {"walkDown":walkDown
    ,"walkUp":walkUp
    ,"walkLeft":walkLeft
    ,"walkRight":walkRight
    ,"grassDown":grassDown
    ,"grassUp":grassUp
    ,"grassLeft":grassLeft
    ,"grassRight":grassRight
    ,"talkB":talkB
    ,"talkA":talkA
    ,"flounder":flounder
    ,"pokemonCenter":pokemonCenter}