fisherman_ivan := [["walkRight",6] ; heal and take out homies
    ,["walkUp",14]
    ,["walkLeft",4]
    ,["walkUp",1]
    ,["w",180]
    ,["walkUp",8]
    ,["talkA",6]
    ,["w",300]
    ,["talkB",5]
    ,["walkRight",2]
    ,["walkUp",1]
    ,["talkA",1]
    ,["w",180]
    ,["talkA",2]
    ,["walkDown",1]
    ,["talkA",1]
    ,["w",180]
    ,["talkA",2]
    ,["walkRight",1]
    ,["talkA",2]
    ,["walkRight",1]
    ,["talkA",2]
    ,["walkRight",1]
    ,["talkA",2]
    ,["walkRight",1]
    ,["talkA",2]
    ,["talkB",6]
    ,["walkLeft",2]
    ,["walkDown",8]
    ,["w",180]
    ,["walkRight",4]
    ,["walkDown",13]
    ,["walkLeft",6]
    ,["walkDown",28]
    ,["walkRight",17]
    ,["walkDown",1]
    ,["talkA",1]
    ,["talkB",20]
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",35]
    ,["talkB",15]
    ,["talkA",35]
    ,["talkB",15]
    ,["talkA",35]
    ,["talkB",15]]

twins_torchic := [["walkLeft",6]
    ,["walkDown",12]
    ,["walkRight",2]
    ,["talkA",1]
    ,["talkB",20] ; TURN 1: torchic needs to Ember LOTAD
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",1]
    ,["walkRight",1]
    ,["talkA",1]
    ,["talkA",3] ; do whatever on burner. he might die. if so, switch
    ,["talkB",30] ; could be a LOT of leveling
    ,["walkDown",1]
    ,["walkLeft",1]
    ,["talkA",2]
    ,["talkB",10]
    ,["walkUp",1] ; TURN 2 Hit Lotad again (or maybe seedot if lotad died)
    ,["talkA",2]
    ,["walkRight",1]
    ,["talkA",1]
    ,["talkA",3] ; do whatever on burner. he might die. if so, switch
    ,["talkB",30]
    ,["walkDown",2]
    ,["walkLeft",1]
    ,["talkA",2]
    ,["talkB",10]
    ,["walkUp",2] ; TURN 3 Hit seedot
    ,["talkA",2]
    ,["walkLeft",1]
    ,["talkA",1]
    ,["talkA",3] ; do whatever on burner. 
    ,["talkB",30] ; torchic will be trying to learn peck. He might, he might not. Overwrite tackle:
    ,["talkA",15]
    ,["talkB",30]]

bc_jose_torchic := [["walkLeft",8]
    ,["walkDown",4]
    ,["walkUp",25]
    ,["walkLeft",8]
    ,["walkUp",18] ; buy some potions
    ,["walkRight",1]
    ,["walkUp",1]
    ,["w",180]
    ,["walkUp",6]
    ,["walkLeft",1]
    ,["talkA",3]
    ,["walkDown",1]
    ,["talkA",1]
    ,["walkUp",4]
    ,["talkA",4]
    ,["talkB",7]
    ,["walkDown",7]
    ,["w",180] ; heal
    ,["walkRight",4]
    ,["walkUp",13]
    ,["walkLeft",4]
    ,["walkUp",1]
    ,["w",180]
    ,["pokemonCenter",1]
    ,["walkRight",7]
    ,["walkUp",35]
    ,["walkRight",31]
    ,["walkDown",8]
    ,["grassRight",7]
    ,["w",1200] ; catch Jose's eye
    ,["talkB",20]
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",1]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]]

youngster_joey_torchic := [["grassLeft",8]
    ,["walkLeft",2]
    ,["walkUp",11]
    ,["walkRight",7]
    ,["walkUp",1]
    ,["walkRight",4]
    ,["w",1200] ; catch joey's eye
    ,["talkB",20]
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",1] ; ember 1. might kill, but if not need to switch
    ,["talkB",15] ; either way, send in a burner i guess
    ,["walkRight",1]
    ,["talkA",1]
    ,["walkRight",1]
    ,["talkA",2] ; send in burner
    ,["talkA",60] ; burner dead or time to switch
    ,["talkB",1]
    ,["walkRight",1]
    ,["talkA",2]
    ,["talkB",1]
    ,["walkRight",1]
    ,["talkA",2]
    ,["talkB",8]
    ,["walkUp",1]
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",1]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]]

lass_haley_torchic := [["walkLeft",7]
    ,["walkDown",3]
    ,["walkLeft",34]
    ,["walkDown",37]
    ,["walkLeft",7]
    ,["walkUp",1]
    ,["w",180]
    ,["pokemonCenter",1]
    ,["walkRIght",4]
    ,["walkDown",14]
    ,["walkLeft",6]
    ,["walkDown",27]
    ,["walkRight",10]
    ,["walkDown",15]
    ,["walkRight",9]
    ,["walkDown",12]
    ,["w",240]
    ,["talkB",20]
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",1]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]]

youngster_josh_torchic := [["walkUp",12]
    ,["walkLeft",10]
    ,["walkUp",24]
    ,["walkLeft",10]
    ,["walkUp",31]
    ,["walkRight",3]
    ,["walkUp",1]
    ,["w",180]
    ,["pokemonCenter",1]
    ,["walkRight",7]
    ,["walkUp",24]
    ,["walkRight",8]
    ,["walkUp",1]
    ,["w",180]
    ,["talkB",20]
    ,["walkUp",10]
    ,["talkB",20]
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",1] ; ember 1
    ,["talkB",15]
    ,["talkA",2] ; ember 2
    ,["talkB",15]
    ,["talkA",2] ; ember 3
    ,["talkB",15]
    ,["talkA",2] ; ember 4
    ,["talkB",15]
    ,["talkA",2] ; ember 5
    ,["talkB",15]]

youngster_tommy_torchic := [["walkDown",12]
    ,["w",180]
    ,["walkLeft",8]
    ,["walkDown",24]
    ,["walkLeft",7]
    ,["walkUp",1]
    ,["w",180]
    ,["pokemonCenter",1]
    ,["walkRight",7]
    ,["walkUp",24]
    ,["walkRight",8]
    ,["walkUp",1]
    ,["w",180]
    ,["walkUp",16]
    ,["walkLeft",5]
    ,["talkB",15]
    ,["talkA",1]
    ,["walkDown",1]
    ,["talkA",100]
    ,["talkB",10]]

schoolkid_georgia_torchic := [["walkLeft",2]
    ,["walkUp",11]
    ,["walkRight",5]
    ,["talkB",20]
    ,["talkA",2]
    ,["talkB",20] ; easy one-shot with double kick. now heal
    ,["walkDown",12]
    ,["walkRight",1]
    ,["walkDown",13]
    ,["w",180]
    ,["walkLeft",8]
    ,["walkDown",24]
    ,["walkLeft",7]
    ,["walkUp",1]
    ,["w",180]
    ,["pokemonCenter",1]]

hiker_clark_torchic := [["walkRight",7]
    ,["walkUp",35]
    ,["walkRight",31]
    ,["walkDown",6]
    ,["walkRight",2]
    ,["grassRight",5]
    ,["walkRight",1]
    ,["grassRight",4]
    ,["walkRight",7]
    ,["walkDown",3]
    ,["grassRight",7]
    ,["grassUp",7] ; 
    ,["grassRight",17] 
    ,["walkUp",1]
    ,["talkA",2] ; two double kicks
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]]

to_roxanne_torchic :=[["grassLeft",20] ; get items (dont need them though) and heal 
    ,["grassDown",6]
    ,["grassLeft",3]
    ,["walkLeft",15]
    ,["grassUp",2]
    ,["walkUp",1]
    ,["grassLeft",5]
    ,["walkLeft",6]
    ,["walkUp",4]
    ,["walkLeft",30]
    ,["walkDown",47]
    ,["walkLeft",9]
    ,["walkDown",30]
    ,["walkRight",10]
    ,["walkDown",15]
    ,["walkRight",8]
    ,["walkDown",11]
    ,["walkLeft",41]
    ,["walkUp",18]
    ,["walkRight",1]
    ,["grassUp",2]
    ,["talkA",6] ; pokeball
    ,["walkUp",1]
    ,["grassRight",2]
    ,["talkA",6] ; super potion
    ,["walkRight",1]
    ,["grassRight",2]
    ,["grassUp",5]
    ,["walkUp",1]
    ,["talkA",6] ; X Att
    ,["grassDown",5]
    ,["grassleft",7]
    ,["grassDown",2]
    ,["walkDown",25]
    ,["walkRight",15]
    ,["walkUp",4]
    ,["walkRight",26]
    ,["walkUp",12]
    ,["walkLeft",9]
    ,["walkUp",24]
    ,["walkLeft",10]
    ,["walkUp",31]
    ,["walkRight",3]
    ,["walkUp",1]
    ,["w",180]
    ,["pokemonCenter",1]
    ,["walkRight",7]
    ,["walkUp",24]
    ,["walkRight",8]
    ,["walkUp",1]
    ,["w",180]
    ,["walkUp",16]
    ,["walkLeft",7]
    ,["walkUp",12]
    ,["walkRight",7]
    ,["walkUp",7]]

roxanne_torchic := [["talkA",1]
    ,["w",600]
    ,["talkB",25]
    ,["talkA",2] ; first, DK. may kill, may not
    ,["w",600] ; if not, heal here
    ,["walkLeft",1]
    ,["talkA",5]
    ,["w",600]
    ,["walkUp",1]
    ,["talkA",2] ; DK will kill
    ,["talkB",15] ; now DK nosepass a few times
    ,["talkA",2]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",15]
    ,["talkA",2]
    ,["talkB",35]]

rustboro_torchic := [fisherman_ivan,twins_torchic,bc_jose_torchic,youngster_joey_torchic,lass_haley_torchic,youngster_josh_torchic,youngster_tommy_torchic,schoolkid_georgia_torchic,hiker_clark_torchic,to_roxanne_torchic,roxanne_torchic]


; roxanne_torchic : = []